version: "2.0"
services:
  db:
    image: mariadb
    hostname: database
    restart: always
    container_name: "im_db"
    environment:
      MYSQL_ROOT_PASSWORD: BDYgS4H4ZMHUKzRnw7GBbnH6p
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    volumes:
      - "./config/.:/etc/mysql/conf.d"
      - "./dbscripts/.:/docker-entrypoint-initdb.d/."
      - "./dbdata/.:/var/lib/mysql/."
  issues: # image that helps traking issues.
    image: redmine
    hostname: redmine
    restart: always
    container_name: "im_redmine"
    environment:
      REDMINE_DB_MYSQL: im_db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
#    depends_on:
#      - db
    volumes:
      - "./redmine-plugins:/usr/src/redmine/plugins/."
  phpmyadmin: #myadmin
    image: phpmyadmin/phpmyadmin
    hostname: myadmin
    restart: always
    container_name: "im_myadmin"
    environment:
      PMA_HOST: im_db
    depends_on:
      - db
  mail: #mail service
    image: roundcube/roundcubemail:elastic
    hostname: roundcube
    restart: always
    container_name: "im_mail"
    environment:
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_DB_HOST: im_db
      ROUNDCUBEMAIL_DB_USER: roundcube
      ROUNDCUBEMAIL_DB_PASSWORD: roundcube
      ROUNDCUBEMAIL_DB_NAME: roundcube
    depends_on:
      - db
  dns: #bind dns server
      image: sameersbn/bind:9.11.3-20190315
      hostname: bind
      restart: always
      container_name: "im_bind"
      environment:
        ROOT_PASSWORD: BDYgS4H4ZMHUKzRnw7GBbnH6p
      ports:
#        - "53:53/tcp"
#        - "53:53/udp"
        - "10000:10000"
      volumes:
        - "./binddata/.:/data/."
  tensorflow: # tensorflow image
    image: tensorflow/tensorflow:nightly-py3-jupyter
    hostname: tensorflow
    restart: always
    container_name: "im_tensorflow"
    depends_on:
      - reverse
    ports:
      - "8888:8888"
    volumes:
      - "./tensorflow/.:/tf/."
      - "./tensorflow/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py"
    command:
      - /tf/startup.sh
    devices:
      - "/dev/video0:/dev/video0"
  handwritting:
    image: richarvey/nginx-php-fpm
    hostname: handwritting
    restart: always
    container_name: "im_handwritting"
    depends_on:
      - reverse
    volumes:
      - "./tensorflow/canvas/.:/var/www/html/."
      - "./tensorflow/uploads/.:/var/www/html/uploads/."
  reverse: #image that helps configure reverse proxy
    image: haproxy
    hostname: haproxy
    restart: always
    container_name: "im_haproxy"
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dns
